FROM alpine-java:base
MAINTAINER sjayapal@skminfotek.com
COPY /Users/sathishjayapal/files/contract_time_webmod.war /Users/sathishjayapal/IdeaProjects/Contractor_Timer/contract_time_webmod/target/
ENV SPRING_APPLICATION_JSON='{"spring": {"cloud": {"config": {"server": \
    {"git": {"uri": "/var/lib/spring-cloud/config-repo", "clone-on-start": true}}}}}}'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-war", "/opt/spring-cloud/lib/contract_time_webmod.war"]
VOLUME /var/lib/spring-cloud/config-repo
EXPOSE 8888